name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      env:
        DOCKER_CLI_AK_ENV: 1  # This is used to enable Docker credential helper

    - name: Build Docker image
      run: docker build -t your-docker-username/shivi-wp:latest .
      working-directory: .

    - name: Push Docker image to Docker Hub
      run: docker push your-docker-username/shvi-wp:latest

    - name: Clean up
      run: docker logout
